# Generated by Django 6.0.3 on 2026-03-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driver', models.CharField(max_length=100, verbose_name='Введите свое ФИО:')),
                ('drive_license', models.BooleanField(default=False, verbose_name='У вас есть права (Да/Нет) ')),
                ('photo', models.ImageField(upload_to='drivers/', verbose_name='Всатвьте фото')),
                ('data_birth', models.DateField(verbose_name='Введите дату рождения:')),
                ('experience', models.PositiveIntegerField(max_length=3, verbose_name='Водительский стаж:')),
                ('choices_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_categories.cars')),
            ],
        ),
    ]
