# Generated by Django 6.0.3 on 2026-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=50, verbose_name='укажите название машины')),
                ('description', models.TextField(verbose_name='укажите описание машины')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='загрузите изображение')),
                ('category_car', models.CharField(choices=[('седан', 'седан'), ('хэтчбек', 'хэтчбек'), ('кроссовер', 'кроссовер'), ('внедорожник', 'внедорожник'), ('купе', 'купе'), ('кабриолет', 'кабриолет'), ('универсал', 'универсал'), ('минивэн', 'минивэн'), ('пикап', 'пикап'), ('спорткар', 'спорткар')], max_length=100, verbose_name='выберите категорию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'машину',
                'verbose_name_plural': 'машины',
            },
        ),
    ]
