# Generated by Django 6.0.3 on 2026-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
